package logearse1;

import java.math.BigInteger;  
import java.nio.charset.StandardCharsets; 
import java.security.MessageDigest;  
import java.security.NoSuchAlgorithmException;  
  
// Java program to calculate SHA hash value  
  
public class Sha256 {
    
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException 
    {  
        // Metodo estatico getInstance asigna SHA-256 hash
        MessageDigest md = MessageDigest.getInstance("SHA-256");  
  
        // Llamamos el metodo digest()
        // Calcular el mensaje encriptado de un input
        // y retornamos un arreglo de bytes
        return md.digest(input.getBytes(StandardCharsets.UTF_8));  
    }
    public static String toHexString(byte[] hash) 
    {
        // Convierte el arreglo de bytes a representacion signum
        BigInteger number = new BigInteger(1, hash);  
        
        // Convierte el mensaje encriptado a sistema hexadecimal
        StringBuilder hexString = new StringBuilder(number.toString(16));  
        
        while (hexString.length() < 32)  
        {  
            hexString.insert(0, '0');  
        }  
  
        return hexString.toString();  
    }
      
  
      
    public static void main(String args[]) 
    {  
        try 
        { 
            System.out.println("HashCode Generated by SHA-256 for:");  
            String u1="Hola";
            
            long startTime = System.nanoTime();
            
            System.out.println("\n" + u1 + " : " + toHexString(getSHA(u1)));
            
            long endTime   = System.nanoTime();
            long totalTime = endTime - startTime;
            System.out.println("Tiempo: "+totalTime*Math.pow(10, -9));
            
            //System.out.println(toHexString(getSHA(u1)).length());
            String u2 = "Discreta";  
            System.out.println("\n" + u2 + " : " + toHexString(getSHA(u2)));  
        } 
        // For specifying wrong message digest algorithms  
        catch (NoSuchAlgorithmException e) {  
            System.out.println("Exception thrown for incorrect algorithm: " + e);  
        }  
    }
    //0.016111599
    // 0.014036488000000001
    //0.017181418
    //0.016175472
    
}